// ==========================================
// i18n: ระบบแปลภาษา (TH / EN) สำหรับ 67-AEGIS (Formal Version)
// ==========================================

const translations = {
    th: {
        "nav_home": "หน้าหลัก",
        "nav_lab": "ห้องปฏิบัติการ",
        "nav_search": "ตรวจสอบและแจ้งเบาะแส",
        "nav_news": "ข่าวสารความมั่นคงปลอดภัย",
        "nav_help": "ศูนย์ให้ความช่วยเหลือ",
        "nav_login": "เข้าสู่ระบบ / ข้อมูลส่วนตัว",
        "hero_title": "ระบบประเมินช่องโหว่และแจ้งเตือนภัยคุกคามทางไซเบอร์",
        "hero_desc": "แพลตฟอร์มศูนย์กลางสำหรับการวิเคราะห์ไฟล์ต้องสงสัย ตรวจสอบประวัติอาชญากรรมทางเทคโนโลยี และประสานงานรับความช่วยเหลือจากเครือข่ายผู้เชี่ยวชาญ",
        "card_lab_title": "ห้องปฏิบัติการวิเคราะห์ (The Lab)",
        "card_lab_body": "ศูนย์ปฏิบัติการวิเคราะห์โครงสร้างไฟล์ต้องสงสัย (รองรับนามสกุล .apk, .pdf, .exe) เพื่อตรวจหาความผิดปกติและมัลแวร์แฝง",
        "btn_enter_lab": "เข้าสู่ห้องปฏิบัติการ",
        "card_search_title": "ระบบตรวจสอบและแจ้งเบาะแส",
        "card_search_body": "บริการตรวจสอบประวัติอาชญากรรมทางเทคโนโลยี บัญชีม้า และพื้นที่สำหรับแจ้งเบาะแสการฉ้อโกงเพื่อรวบรวมเข้าสู่ฐานข้อมูลส่วนกลาง",
        "btn_search_report": "ตรวจสอบข้อมูล / แจ้งเบาะแส",
        "card_news_title": "ศูนย์รวมข่าวสารและสถิติ",
        "card_news_body": "กระดานแจ้งเตือนภัยคุกคามทางไซเบอร์และสถิติที่สำคัญ พร้อมการอัปเดตข้อมูลตามเวลาจริง (Real-time) จากเครือข่ายผู้ใช้งาน",
        "btn_view_news": "ติดตามข่าวสารล่าสุด",
        "lab_header_title": "🔬 ห้องปฏิบัติการวิเคราะห์ไฟล์ (The Lab)",
        "lab_header_desc": "ระบบจะไม่เปิดอ่านเนื้อหาภายในไฟล์ของคุณ แต่จะตรวจสอบโครงสร้างระดับไบต์ (Magic Bytes) เพื่อค้นหาความผิดปกติและมัลแวร์แฝง",
        "lab_dropzone_title": "ลากไฟล์มาวางที่นี่",
        "lab_dropzone_or": "หรือคลิกเพื่อเลือกไฟล์จากอุปกรณ์ของคุณ",
        "lab_dropzone_support": "รองรับไฟล์: .apk, .pdf, .exe, .zip (ขนาดไม่เกิน 50MB)",
        "lab_security_badge": "🔒 ปลอดภัย 100%: ไฟล์ของคุณจะไม่ถูกบันทึกหรือถูกเปิดอ่านเนื้อหาบนเซิร์ฟเวอร์ส่วนกลาง",
        "lab_result_title": "📑 รายงานผลการวิเคราะห์ทางนิติวิทยาศาสตร์ดิจิทัล (Forensic Report)",
        "lab_result_badge_danger": "ตรวจพบความเสี่ยงระดับสูง",
        "lab_label_filename": "ชื่อไฟล์ที่อัปโหลด:",
        "lab_label_ext": "นามสกุลไฟล์ที่ระบุ:",
        "lab_label_magic": "ประเภทไฟล์ที่แท้จริง (Magic Bytes):",
        "lab_label_hash": "รหัสดิจิทัล (SHA-256 Hash):",
        "lab_advice_title": "ข้อแนะนำด้านความปลอดภัย:",
        "lab_advice_desc": "ไฟล์นี้มีการใช้นามสกุลปลอมเพื่อหลอกลวงให้ผู้ใช้งานติดตั้งแอปพลิเคชันอันตราย (มัลแวร์ขโมยข้อมูล) ห้ามเปิดหรือติดตั้งไฟล์นี้ลงในอุปกรณ์โดยเด็ดขาด!",
        "lab_btn_report": "รายงานไฟล์นี้ลงสู่ฐานข้อมูลภัยคุกคาม",
        "search_header_title": "ระบบตรวจสอบฐานข้อมูลภัยคุกคาม",
        "search_header_desc": "ตรวจสอบเลขบัญชีธนาคาร เบอร์โทรศัพท์ หรือลิงก์ที่น่าสงสัย ก่อนดำเนินการทำธุรกรรมใดๆ",
        "search_placeholder": "กรอกเลขบัญชี, เบอร์โทรศัพท์, หรือลิงก์...",
        "search_btn_check": "ตรวจสอบข้อมูล",
        "search_hint": "💡 ข้อแนะนำ: คุณสามารถคัดลอกข้อความแชทที่มีเลขบัญชีมาวางได้ทันที ระบบมี AI ช่วยคัดแยกตัวเลขโดยอัตโนมัติ",
        "search_result_risk": "ระดับความเสี่ยง: สูงมาก (อันตราย)",
        "search_result_desc": "ตรวจพบประวัติในฐานข้อมูลบัญชีดำของ 67-AEGIS",
        "search_result_report_count": "สถิติการรายงาน",
        "search_label_query": "ข้อมูลที่ตรวจสอบ:",
        "search_label_type": "ประเภทภัยคุกคาม:",
        "search_label_name": "ข้อมูลผู้ต้องสงสัย:",
        "search_label_behavior": "พฤติการณ์ที่ตรวจพบ:",
        "search_label_advice": "คำแนะนำ: หากท่านตกเป็นเหยื่อ กรุณารวบรวมหลักฐานเพื่อแจ้งความ หรือติดต่อสายด่วน 1441 ทันที",
        "search_cta_title": "ไม่พบข้อมูล หรือท่านเพิ่งตกเป็นเหยื่อ?",
        "search_cta_desc": "ร่วมเป็นส่วนหนึ่งในการปกป้องสังคม แจ้งเบาะแสบัญชีม้าหรือมัลแวร์เข้าสู่ระบบส่วนกลาง เพื่อป้องกันไม่ให้เกิดผู้เสียหายรายใหม่",
        "search_btn_report": "แจ้งเบาะแสภัยคุกคาม",
        "search_modal_title": "แบบฟอร์มรายงานภัยคุกคาม",
        "search_modal_desc": "ข้อมูลของท่านจะถูกรวบรวมเพื่อการวิเคราะห์และป้องกันการก่ออาชญากรรมทางเทคโนโลยีในเครือข่าย 67-AEGIS",
        "search_form_type": "ประเภทของภัยคุกคาม",
        "search_form_type_bank": "บัญชีธนาคาร (บัญชีม้า)",
        "search_form_type_phone": "เบอร์โทรศัพท์ (คอลเซ็นเตอร์ / SMS หลอกลวง)",
        "search_form_type_link": "ลิงก์เว็บไซต์ปลอม (Phishing / Malware)",
        "search_form_data": "ข้อมูลเป้าหมาย (เลขบัญชี / เบอร์โทร / URL)",
        "search_form_data_ph": "กรอกข้อมูลที่นี่...",
        "search_form_behavior": "รายละเอียดพฤติการณ์ (โดยสังเขป)",
        "search_form_behavior_ph": "ตัวอย่าง: หลอกให้โอนเงินค่ามัดจำสินค้าแล้วบล็อกช่องทางการติดต่อ...",
        "search_form_submit": "ส่งข้อมูลเข้าสู่ฐานข้อมูลส่วนกลาง",
        "news_header_title": "ศูนย์รวมข่าวสารและสถิติภัยคุกคาม",
        "news_header_desc": "อัปเดตสถานการณ์ความมั่นคงปลอดภัยไซเบอร์ล่าสุดและสถิติจากเครือข่ายภาคประชาชน",
        "news_main_title": "🌐 ข่าวสารความมั่นคงปลอดภัยระดับโลก",
        "news_main_desc": "ติดตามข่าวสารด้านความมั่นคงปลอดภัยไซเบอร์แบบตามเวลาจริง (Global Threat Intelligence)",
        "help_header_title": "ศูนย์ให้ความช่วยเหลือและประสานงาน",
        "help_header_desc": "ปรึกษาผู้ช่วยอัจฉริยะเบื้องต้น หรือขอรับการสนับสนุนจากเครือข่ายผู้เชี่ยวชาญ 67-AEGIS",
        "help_bot_name": "ผู้ช่วยอัจฉริยะ \"คุณอาทิตย์\"",
        "help_bot_status": "ระบบพร้อมให้บริการ",
        "help_bot_welcome1": "สวัสดีครับ ผม \"อาทิตย์\" ผู้ช่วยส่วนตัวจาก 67-AEGIS 🛡️",
        "help_bot_welcome2": "หากท่านพบธุรกรรมที่น่าสงสัย หรือตกเป็นผู้เสียหายจากอาชญากรรมทางเทคโนโลยี กรุณาพิมพ์รายละเอียดให้ผมทราบ ผมพร้อมให้คำแนะนำขั้นตอนการอายัดบัญชีและกระบวนการทางกฎหมายครับ",
        "help_bot_placeholder": "พิมพ์ข้อความปรึกษาที่นี่...",
        "help_kyc_intro_title": "เครือข่ายอาสาสมัครและผู้เชี่ยวชาญ",
        "help_kyc_intro_desc1": "พื้นที่ควบคุมด้านความปลอดภัย สำหรับประสานงานและขอรับความช่วยเหลือจากผู้เชี่ยวชาญด้านกฎหมายและไอที",
        "help_kyc_intro_desc2_bold": "มาตรการความปลอดภัยขั้นสูงสุด:",
        "help_kyc_intro_desc2": "ผู้ใช้งานจำเป็นต้องผ่านกระบวนการทำความรู้จักลูกค้า (KYC) เพื่อยืนยันตัวตน ป้องกันการแฝงตัวของอาชญากรไซเบอร์",
        "help_kyc_btn_start": "เริ่มต้นกระบวนการยืนยันตัวตน",
        "help_kyc_form_title": "การยืนยันตัวตน (KYC)",
        "help_kyc_form_role": "ระบุบทบาทการใช้งานของท่าน",
        "help_role_victim": "ผู้ขอรับความช่วยเหลือ",
        "help_role_victim_desc": "(ผู้เสียหาย / ผู้แจ้งเบาะแส)",
        "help_role_volunteer": "เครือข่ายผู้เชี่ยวชาญ",
        "help_role_volunteer_desc": "(อาสาสมัครกฎหมาย / ไอที)",
        "help_kyc_id_label": "หมายเลขประจำตัวประชาชน (13 หลัก)",
        "help_kyc_bio_label": "การยืนยันอัตลักษณ์ทางชีวมิติ (Facial Biometrics)",
        "help_kyc_bio_btn_open": "เปิดกล้องเพื่อยืนยันใบหน้า",
        "help_kyc_bio_btn_snap": "บันทึกภาพเพื่อยืนยัน",
        "help_kyc_btn_submit": "ส่งข้อมูลยืนยันตัวตนเข้าสู่ระบบ",
        "help_dash_title": "กระดานรับเรื่องประสานงาน (Dashboard)",
        "help_dash_case1": "เคส #1042: แจ้งความร้องทุกข์คดีฉ้อโกง",
        "help_dash_case1_desc": "ผู้เสียหาย: คุณเอ • สถานะ: รอการตอบรับ 5 นาที",
        "help_dash_case2": "เคส #1045: ตรวจสอบมัลแวร์ในอุปกรณ์",
        "help_dash_case2_desc": "ผู้เสียหาย: คุณบี • สถานะ: รอการตอบรับ 2 นาที",
        "help_dash_btn_accept": "รับดูแลเคสนี้",
        "help_p2p_title": "ห้องสนทนาเข้ารหัส (Secure P2P Chat)",
        "help_p2p_secure_msg": "การยืนยันตัวตนเสร็จสมบูรณ์ ช่องทางนี้ได้รับการเข้ารหัสข้อมูล (End-to-End Encryption)",
        "help_p2p_placeholder": "พิมพ์ข้อความสนทนาที่นี่...",
        "login_info_title": "ร่วมเป็น \"พลเมืองดีไซเบอร์\"",
        "login_info_desc": "ระบบ 67-AEGIS ขับเคลื่อนด้วยข้อมูลจากชุมชน การสมัครสมาชิกจะช่วยให้ท่านสามารถ:",
        "login_info_list1": "รายงานบัญชีม้าและลิงก์อันตรายเข้าสู่ฐานข้อมูลส่วนกลาง",
        "login_info_list2": "สะสมคะแนนความน่าเชื่อถือ (Trust Score)",
        "login_info_list3": "ติดตามสถานะการดำเนินการของภัยคุกคามที่ท่านรายงาน",
        "login_info_list4": "เข้าถึงประวัติการวิเคราะห์ไฟล์ย้อนหลังทางนิติวิทยาศาสตร์",
        "login_tab_login": "เข้าสู่ระบบ",
        "login_tab_register": "ลงทะเบียน",
        "login_lbl_email": "อีเมล (Email)",
        "login_ph_email": "example@mail.com",
        "login_lbl_pass": "รหัสผ่าน (Password)",
        "login_ph_pass": "••••••••",
        "login_lbl_remember": "จดจำฉันไว้ในระบบ",
        "login_link_forgot": "ลืมรหัสผ่าน?",
        "login_btn_submit": "เข้าสู่ระบบ",
        "reg_lbl_name": "ชื่อ-นามสกุล",
        "reg_ph_name": "ตัวอย่าง: สมชาย ส.",
        "reg_lbl_phone": "เบอร์โทรศัพท์",
        "reg_ph_phone": "08XXXXXXXX (10 หลัก)",
        "reg_lbl_pass": "ตั้งรหัสผ่าน",
        "reg_ph_pass": "ความยาวอย่างน้อย 8 ตัวอักษร",
        "reg_lbl_accept": "ฉันยอมรับ ",
        "reg_link_terms": "ข้อตกลงและนโยบายความเป็นส่วนตัว",
        "reg_btn_submit": "ลงทะเบียนและเริ่มใช้งาน",
        "forgot_title": "ลืมรหัสผ่านใช่หรือไม่?",
        "forgot_desc": "กรุณายืนยันตัวตนด้วยชื่อผู้ใช้และอีเมลที่ลงทะเบียนไว้ เพื่อดำเนินการตั้งรหัสผ่านใหม่",
        "forgot_lbl_user": "ชื่อผู้ใช้ (Username)",
        "forgot_ph_user": "กรอกชื่อผู้ใช้ของท่าน",
        "forgot_lbl_email": "อีเมลที่ลงทะเบียน",
        "forgot_lbl_newpass": "ตั้งรหัสผ่านใหม่",
        "forgot_ph_newpass": "รหัสผ่านใหม่อย่างน้อย 6 ตัวอักษร",
        "forgot_btn_submit": "บันทึกรหัสผ่านใหม่",
        "forgot_link_back": "กลับไปหน้าเข้าสู่ระบบ",
        "terms_title": "ข้อตกลงและนโยบายความเป็นส่วนตัว (Privacy Policy)",
        "terms_p1": "ยินดีต้อนรับสู่ 67-AEGIS (Cyber-Vulnerability Assessment & Forensic Alert System) แพลตฟอร์มส่วนกลางสำหรับการตรวจสอบและรายงานภัยคุกคามทางไซเบอร์",
        "terms_h1": "1. การเก็บรวบรวมข้อมูลส่วนบุคคล",
        "terms_p2": "ระบบจะทำการจัดเก็บข้อมูลพื้นฐานของท่าน ได้แก่ ชื่อ-นามสกุล อีเมล และเบอร์โทรศัพท์ เพื่อใช้ในการยืนยันตัวตน รหัสผ่านของท่านจะถูกเข้ารหัสขั้นสูง (Hashing) ตามมาตรฐานสากล",
        "terms_h2": "2. นโยบายการรายงาน (Crowdsourcing Policy)",
        "terms_p3": "ผู้ใช้งานตกลงที่จะรายงานข้อมูลที่เป็นความจริง ห้ามมิให้ผู้ใช้งานส่งข้อมูลอันเป็นเท็จเข้าสู่ระบบส่วนกลาง ทีมงานขอสงวนสิทธิ์ในการระงับบัญชีหากตรวจพบการกระทำผิด",
        "terms_h3": "3. การนำข้อมูลไปใช้งาน",
        "terms_p4": "ข้อมูลภัยคุกคามที่ท่านรายงาน จะถูกเปิดเผยสู่สาธารณะเพื่อให้ผู้ใช้งานท่านอื่นสามารถเฝ้าระวังได้ เพื่อประโยชน์ในการป้องกันอาชญากรรมทางเทคโนโลยี",
        "terms_btn_accept": "ฉันเข้าใจและยอมรับเงื่อนไขทั้งหมด",
        "otp_title": "ยืนยันรหัส OTP",
        "otp_desc": "ระบบได้ส่งรหัส 6 หลักไปยังหมายเลขโทรศัพท์:",
        "otp_btn_verify": "ยืนยันตัวตน",
        "otp_btn_cancel": "ยกเลิกการลงทะเบียน",
        "profile_loading": "กำลังโหลดข้อมูลผู้ใช้งาน...",
        "profile_badge_bronze": "🔰 สมาชิกเครือข่ายเฝ้าระวังระดับเริ่มต้น",
        "profile_thankyou": "ขอขอบพระคุณที่ร่วมเป็นส่วนหนึ่งในเครือข่ายเฝ้าระวังภัยคุกคามทางไซเบอร์ ข้อมูลของท่านมีส่วนสำคัญในการปกป้องผู้ใช้งานท่านอื่นในระบบนิเวศของ 67-AEGIS",
        "profile_stat_trust": "ดัชนีความน่าเชื่อถือ (Trust Score)",
        "profile_stat_report": "รายการที่แจ้งเข้าสู่ฐานข้อมูลส่วนกลาง",
        "profile_btn_search": "ตรวจสอบข้อมูลหรือแจ้งเบาะแสเพิ่มเติม",
        "profile_btn_logout": "ออกจากระบบ"
    },
    en: {
        "nav_home": "Home",
        "nav_lab": "The Lab",
        "nav_search": "Threat Intelligence",
        "nav_news": "Security Bulletins",
        "nav_help": "Support Center",
        "nav_login": "Login / Profile",
        "hero_title": "Cyber-Vulnerability Assessment & Forensic Alert System",
        "hero_desc": "A centralized platform for scanning suspicious files, conducting digital background checks, and facilitating assistance through a network of experts.",
        "card_lab_title": "Forensic Laboratory (The Lab)",
        "card_lab_body": "Upload and analyze the internal structure of suspicious files (.apk, .pdf, .exe) to detect anomalies and embedded malware.",
        "btn_enter_lab": "Enter the Laboratory",
        "card_search_title": "Threat Intelligence & Reporting",
        "card_search_body": "Investigate cybercriminal records, money mule accounts, and report fraudulent activities to our centralized database.",
        "btn_search_report": "Investigate / Report",
        "card_news_title": "Security Bulletins",
        "card_news_body": "Real-time updates on cybersecurity advisories, threat statistics, and incident reports crowdsourced from our network.",
        "btn_view_news": "View Latest Advisories",
        "lab_header_title": "🔬 Forensic File Laboratory (The Lab)",
        "lab_header_desc": "We do not read the internal content of your files. We only inspect the structural integrity (Magic Bytes) to detect anomalies and embedded malware.",
        "lab_dropzone_title": "Drag & Drop File Here",
        "lab_dropzone_or": "or click to select a file from your device",
        "lab_dropzone_support": "Supported formats: .apk, .pdf, .exe, .zip (Max size: 50MB)",
        "lab_security_badge": "🔒 100% Safe: Your files are neither saved nor read on our central servers.",
        "lab_result_title": "📑 Digital Forensic Analysis Report",
        "lab_result_badge_danger": "High Security Risk Detected",
        "lab_label_filename": "Uploaded Filename:",
        "lab_label_ext": "Claimed Extension:",
        "lab_label_magic": "Actual File Type (Magic Bytes):",
        "lab_label_hash": "Digital Signature (SHA-256 Hash):",
        "lab_advice_title": "Security Advisory:",
        "lab_advice_desc": "This file uses a spoofed extension to trick users into installing a malicious application (Infostealer Malware). DO NOT open or execute this file on your device!",
        "lab_btn_report": "Report This File to the Threat Database",
        "search_header_title": "Threat Intelligence Database",
        "search_header_desc": "Verify suspicious bank accounts, phone numbers, or URLs before executing any transactions.",
        "search_placeholder": "Enter account number, phone, or URL...",
        "search_btn_check": "Analyze Data",
        "search_hint": "💡 Tip: You can paste raw chat logs containing account numbers; our system will extract the digits automatically.",
        "search_result_risk": "Risk Level: CRITICAL (Malicious)",
        "search_result_desc": "Match found in the 67-AEGIS central blacklist database.",
        "search_result_report_count": "Total Reports",
        "search_label_query": "Target Data:",
        "search_label_type": "Threat Category:",
        "search_label_name": "Suspect Name:",
        "search_label_behavior": "Reported Behaviors:",
        "search_label_advice": "Advisory: If you have been compromised, gather all evidence and contact cyber police or dial 1441 immediately.",
        "search_cta_title": "No match found, or recently scammed?",
        "search_cta_desc": "Contribute to community defense. Report fraudulent accounts or malicious links to our central system to prevent future victims.",
        "search_btn_report": "Submit Threat Report",
        "search_modal_title": "Threat Incident Report Form",
        "search_modal_desc": "Your submission will be analyzed and integrated into the 67-AEGIS intelligence network to prevent cybercrimes.",
        "search_form_type": "Threat Category",
        "search_form_type_bank": "Bank Account (Money Mule)",
        "search_form_type_phone": "Phone Number (Scam Call / SMS)",
        "search_form_type_link": "Malicious Link (Phishing / Malware)",
        "search_form_data": "Target Information (Account / Phone / URL)",
        "search_form_data_ph": "Enter data here...",
        "search_form_behavior": "Incident Details (Brief)",
        "search_form_behavior_ph": "Example: Deceived into transferring a deposit, then blocked all communications...",
        "search_form_submit": "Submit to Central Database",
        "news_header_title": "Community News & Threat Feed",
        "news_header_desc": "Latest cybersecurity updates and threat statistics gathered from our community network.",
        "news_main_title": "🌐 Global Cybersecurity News",
        "news_main_desc": "Stay informed with real-time updates on global cybersecurity events (Global Threat Intelligence).",
        "help_header_title": "Support & Coordination Center",
        "help_header_desc": "Consult our AI assistant or request support from the 67-AEGIS expert network.",
        "help_bot_name": "AI Assistant \"Arthit\"",
        "help_bot_status": "System Online & Ready",
        "help_bot_welcome1": "Hello, I am \"Arthit\", your virtual assistant from 67-AEGIS 🛡️",
        "help_bot_welcome2": "If you notice suspicious transactions or have fallen victim to cybercrime, please provide the details. I can guide you through account freezing procedures and legal steps.",
        "help_bot_placeholder": "Type your message here...",
        "help_kyc_intro_title": "Expert & Volunteer Network",
        "help_kyc_intro_desc1": "A secure, controlled environment to coordinate and receive assistance from legal and IT professionals.",
        "help_kyc_intro_desc2_bold": "Maximum Security Measures:",
        "help_kyc_intro_desc2": "Users must complete the Know Your Customer (KYC) identity verification process to prevent cybercriminal infiltration.",
        "help_kyc_btn_start": "Initiate Identity Verification",
        "help_kyc_form_title": "Identity Verification (KYC)",
        "help_kyc_form_role": "Specify Your Operational Role",
        "help_role_victim": "Requesting Assistance",
        "help_role_victim_desc": "(Victim / Informant)",
        "help_role_volunteer": "Expert Network",
        "help_role_volunteer_desc": "(Legal / IT Volunteer)",
        "help_kyc_id_label": "National Identification Number (13 Digits)",
        "help_kyc_bio_label": "Facial Biometric Verification",
        "help_kyc_bio_btn_open": "Enable Camera for Verification",
        "help_kyc_bio_btn_snap": "Capture Biometric Data",
        "help_kyc_btn_submit": "Submit Verification Data to System",
        "help_dash_title": "Coordination Dashboard",
        "help_dash_case1": "Case #1042: Fraud Incident Report",
        "help_dash_case1_desc": "Victim: User A • Status: Waiting for 5 mins",
        "help_dash_case2": "Case #1045: Device Malware Inspection",
        "help_dash_case2_desc": "Victim: User B • Status: Waiting for 2 mins",
        "help_dash_btn_accept": "Accept This Case",
        "help_p2p_title": "Secure P2P Chat Room",
        "help_p2p_secure_msg": "Identity verified. This channel is secured with End-to-End Encryption.",
        "help_p2p_placeholder": "Type your message here...",
        "login_info_title": "Become a \"Cyber Citizen\"",
        "login_info_desc": "67-AEGIS is a community-driven platform. Creating an account allows you to:",
        "login_info_list1": "Report money mules and malicious links to the central database",
        "login_info_list2": "Accumulate Trust Score to verify your credibility",
        "login_info_list3": "Track the investigation status of your reported cases",
        "login_info_list4": "Access your digital forensic file analysis history",
        "login_tab_login": "Sign In",
        "login_tab_register": "Register",
        "login_lbl_email": "Email Address",
        "login_ph_email": "example@mail.com",
        "login_lbl_pass": "Password",
        "login_ph_pass": "••••••••",
        "login_lbl_remember": "Remember me",
        "login_link_forgot": "Forgot Password?",
        "login_btn_submit": "Sign In",
        "reg_lbl_name": "Full Name",
        "reg_ph_name": "e.g. John Doe",
        "reg_lbl_phone": "Phone Number",
        "reg_ph_phone": "10 digits (e.g. 08XXXXXXXX)",
        "reg_lbl_pass": "Create Password",
        "reg_ph_pass": "Minimum 8 characters",
        "reg_lbl_accept": "I accept the ",
        "reg_link_terms": "Terms of Service & Privacy Policy",
        "reg_btn_submit": "Register & Get Started",
        "forgot_title": "Forgot Your Password?",
        "forgot_desc": "Please verify your identity with your registered username and email to reset your password.",
        "forgot_lbl_user": "Username",
        "forgot_ph_user": "Enter your username",
        "forgot_lbl_email": "Registered Email",
        "forgot_lbl_newpass": "New Password",
        "forgot_ph_newpass": "Minimum 6 characters",
        "forgot_btn_submit": "Save New Password",
        "forgot_link_back": "Back to Login",
        "terms_title": "Terms of Service & Privacy Policy",
        "terms_p1": "Welcome to 67-AEGIS (Cyber-Vulnerability Assessment & Forensic Alert System), a centralized platform for threat intelligence and reporting.",
        "terms_h1": "1. Data Collection",
        "terms_p2": "The system collects basic information (Name, Email, Phone) for identity verification. Your password is encrypted using advanced hashing algorithms compliant with international standards.",
        "terms_h2": "2. Crowdsourcing Policy",
        "terms_p3": "Users agree to submit truthful information. Submitting false data or using the system for harassment is strictly prohibited and will result in account suspension.",
        "terms_h3": "3. Data Utilization",
        "terms_p4": "Threat intelligence data reported by you will be made public to help protect the community and prevent cybercrimes.",
        "terms_btn_accept": "I understand and accept all terms",
        "otp_title": "OTP Verification",
        "otp_desc": "A 6-digit code has been sent to your phone:",
        "otp_btn_verify": "Verify Identity",
        "otp_btn_cancel": "Cancel Registration",
        "profile_loading": "Loading user data...",
        "profile_badge_bronze": "🔰 Novice Cyber Defender",
        "profile_thankyou": "Thank you for being an active participant in our cyber threat surveillance network. Your contributions are vital to protecting other users within the 67-AEGIS ecosystem.",
        "profile_stat_trust": "Credibility Index (Trust Score)",
        "profile_stat_report": "Reports Submitted to Central Database",
        "profile_btn_search": "Verify Data or Submit New Report",
        "profile_btn_logout": "Sign Out"
    }
};

let currentLang = localStorage.getItem('cvafas_lang') || 'th';

function applyTranslations() {
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[currentLang][key]) {
            element.textContent = translations[currentLang][key];
        }
    });

    const langBtnText = document.getElementById('langBtnText');
    if (langBtnText) {
        langBtnText.textContent = currentLang === 'th' ? 'EN' : 'TH';
    }
}

function toggleLanguage() {
    currentLang = currentLang === 'th' ? 'en' : 'th';
    localStorage.setItem('cvafas_lang', currentLang);
    applyTranslations();
}

document.addEventListener('DOMContentLoaded', () => {
    applyTranslations();
    const btnLangToggle = document.getElementById('btnLangToggle');
    if (btnLangToggle) {
        btnLangToggle.addEventListener('click', (e) => {
            e.preventDefault();
            toggleLanguage();
        });
    }
});